### ISSUE TITLE
看图界面-添加展示全部 dicom 元信息窗口

### ISSUE THREAD

**Issue by JasonDoingGreat** [JancsiTech/Viewers#1]
## Request

**What feature or change would you like to see made?**

- 在进入看图页面后，对每个看图窗口，增加一个 info 按钮，点击后，可弹出 dialog，显示当前窗口展示的序列全部元信息

**Why should we prioritize this feature?**

p0

**Comment by zhengdechang1** [comment]
resolve url : [https://github.com/JancsiTech/Viewers/commit/d4f1ac5c2fe0cf062b0715818837dc4e546e9038](https://github.com/JancsiTech/Viewers/commit/d4f1ac5c2fe0cf062b0715818837dc4e546e9038)
