### ISSUE TITLE
第一个服务器连不上不应该卡死

### ISSUE THREAD

**Issue by jancsitech-zhongya** [JancsiTech/Viewers#2]
如果首要服务器连接不上应该catch住 ，允许切换服务器

**Comment by zhengdechang1** [comment]
resolve in [https://github.com/JancsiTech/Viewers/commit/2440725c1f156b004e35569e2ddb7ce10ac5e72e](https://github.com/JancsiTech/Viewers/commit/2440725c1f156b004e35569e2ddb7ce10ac5e72e)
